export { default as Dummy } from './main/dummy'
export { default as HomeScreen } from './main/home'
export { default as OnBoarding } from './main/onBoarding'
export { default as SignIn } from './main/SignIn'
export { default as CountrySelector } from './main/Signup'
export { default as SplashScreen } from './main/SplashScreen'

export { default as HomeScreens, HomeScreenRoutes } from './home'
export { default as OnboardingScreens, OnboardingScreenRoutes } from './onboarding'
export { default as CardScreens, CardScreenRoutes } from './cards'
export { default as CommonScreens, CommonScreenRoutes } from './common'
export { default as ProfileScreens, ProfileScreenRoutes } from './profile'
export { default as LinkBankScreens } from './linkBank'
