export enum __SCREENS {
	SELF_TRADE_INTRO = 'SELF_TRADE_INTRO',
	SELF_TRADE_DASHBOARD = 'SELF_TRADE_DASHBOARD',
	STOCK_DETAILS = 'STOCK_DETAILS',

	VERIFY_IDENTITY = 'VERIFY_IDENTITY',
	SUCCESS = 'SUCCESS',
	SUCCESS_ALT = 'SUCCESS_ALT',
	ACTIVATE_FINGERPRINT = 'ACTIVATE_FINGERPRINT',

	GROUP_SAVINGS_INTRO = 'GROUP_SAVINGS_INTRO',
	GROUP_SAVINGS_DASHBOARD = 'GROUP_SAVINGS_DASHBOARD',
	GROUP_SAVINGS_CREATE_GROUP = 'GROUP_SAVINGS_CREATE_GROUP',
	GROUP_SAVINGS_VIEW_GROUP = 'GROUP_SAVINGS_VIEW_GROUP',
	GROUP_SAVINGS_PAYMENT_HISTORY = 'GROUP_SAVINGS_PAYMENT_HISTORY',
	GROUP_SAVINGS_COLLECT_INFO_1 = 'GROUP_SAVINGS_COLLECT_INFO_1',
	GROUP_SAVINGS_COLLECT_INFO_2 = 'GROUP_SAVINGS_COLLECT_INFO_2',
	GROUP_SAVINGS_COLLECT_INFO_3 = 'GROUP_SAVINGS_COLLECT_INFO_3',
	GROUP_SAVINGS_TERMS_AND_CONDITIONS = 'GROUP_SAVINGS_TERMS_AND_CONDITIONS',
	GROUP_SAVINGS_UPCOMMING_PAYMENTS = 'GROUP_SAVINGS_UPCOMMING_PAYMENTS',
	GROUP_SAVINGS_ALL_PAYMENTS_COLLECTED = 'GROUP_SAVINGS_ALL_PAYMENTS_COLLECTED',
	GROUP_SAVINGS_RECENT_PAYOUTS = 'GROUP_SAVINGS_RECENT_PAYOUTS',
}

export enum __NAVIGATORS {
	SELF_TRADE = 'SELF_TRADE',
	GROUP_SAVINGS = 'GROUP_SAVINGS',
	HOME = 'Home',
}
